FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    -r admin_api/requirements.txt

CMD ["gunicorn", "news_project.wsgi:application", "--bind", "0.0.0.0:8000"]

